{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-config
  labels:
    app: {{.Values.name}}
data:
{{- if .Values.configmap.enabled }}
  {{- toYaml .Values.configmap.data | nindent 2 }}
{{- end }}
{{- end -}}